project:
    data_name: "franka_mindlab"
    dof: 7
    dataset_dir: "dataset/{data_name}/labeled_data/"
    models_dir: "pipelines/trained_models/franka_mindlab/"
    save_model_dir: "pipelines_transferLearning/trained_models/{data_name}/"


detection_model:
    architecture: 'cnnBiLSTM'
    type: 'm2_cnnBiLSTM_contactDetection'
    version: '64'

    model_init_args:
      num_features: &det_seq 100
      hidden_size: 64
      num_layers: 2
      task: 'detection'

    filename_params:
      gap: 1
      accuracy: 91.19

    filename_params_:
      gap: 15
      accuracy: 86.28
    weights_file_template: 'numLayer{num_layers}_hiddenSize{hidden_size}_seq_num{num_features}_gap{gap}_accuracy{accuracy:.2f}.pth'

    trainer_params:
      window_length: *det_seq
      training_gap: 1
      validation_gap: 5
      epochs: 40
      batch_size: 64
      learning_rate: 0.001
      optimizer: 'Adam'
      early_stop_patience: 2

    evaluator_params:
      window_length: *det_seq
      gap: 1
      batch_size: 2048
      n_majority_voting: 14
      allowable_delay_ms: 150

localization_model:
    architecture: 'cnnBiLSTM'
    type: 'm2_cnnBiLSTM_contactLocalization'
    version: '64'
    
    model_init_args:
      num_features: &loc_seq 350
      hidden_size: 128
      num_layers: 1
      task: 'localization'

    filename_params:
      gap: 1
      accuracy: 93.10

    filename_params_:
      gap: 10
      accuracy: 84.83

    weights_file_template: 'numLayer{num_layers}_hiddenSize{hidden_size}_seq_num{num_features}_gap{gap}_accuracy{accuracy:.2f}.pth'

    trainer_params:
      window_length: *loc_seq
      training_gap: 1
      validation_gap: 5
      epochs: 40
      batch_size: 64
      learning_rate: 0.001
      optimizer: 'Adam'
      early_stop_patience: 3
      
    evaluator_params:
      window_length: *loc_seq
      gap: 1
      batch_size: 2048
      n_majority_voting: 14
      allowable_delay_ms: 150

labels:
    link7: 7
    link6: 6
    link5: 5
    link4: 4
    link3: 3
    link2: 2
    link1: 1
    no_contact: 0